require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native/scripts/react_native_pods'

platform :ios, '13.0'
prepare_react_native_project!

target 'BraintreeDropInExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BraintreeDropInExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
